### ISSUE TITLE
Need to target netstandard2.0 instead of cross-compiling

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/SHiPS#104]
Right now you're basically shipping two separate modules (one for Windows PowerShell, and one for PowerShell Core). The problem is that this forces anyone who wants to write a *binary* module to _also_ ship two ...

There's no way for anyone to make a cross-platform binary (targeting netstandard2.0) while referencing SHiPS (or your copies of P2F) when your assemblies are targeted at netcoreapp2.0

This forces us to go against best practices and leaves us forced to target the same pre-release System.Management.Automation assemblies you're targeting.

**Comment by jianyunt** [comment]
It's using .netstandard 2.0 now.
