### ISSUE TITLE
FileSystem Question

### ISSUE THREAD

**Issue by crshnbrn66** [PowerShell/SHiPS#67]
In the example for filesystem the -root parameter when creating the drive specifies the name of the module filesystem#C this refers to the module name and implementing class correct? If that is true.. How do you do something like this: 

 new-psdrive test -PSProvider SHiPS -Root "filesystem#c:\temp"
Do you add an overload to the constructors? 
C([string]$name): base($name),fileinfo($filename)
    {
    }

I tried that and got an error:
new-psdrive test -psprovider Ships -root "filesystem#c#c:\temp"
new-psdrive : Found invalid root format 'filesystem#c#c:\temp'. The supported format is 'Module#Class'.

Must you make a class for each thing you want to open?? Or is that the purpose of the dynamic example?

**Comment by jianyunt** [comment]
@crshnbrn66 Yes you are right.  The format is 'Module#Class'. In this case, ["C"](https://github.com/PowerShell/SHiPS/blob/development/samples/FileSystem/FileSystem.psm1#L19) is the class.  If you want to support c:\temp, you need to define a class 'Temp'.  In the GetChildItem() of the root Class C , you return 'Temp', similar to [familytree sample](https://github.com/PowerShell/SHiPS/blob/development/samples/FamilyTree/FamilyTree.psm1#L69).

**Comment by crshnbrn66** [comment]
Is there any way to pass a Path to my provider then? .

**Comment by jianyunt** [comment]
Not supported by SHiPS.
