### ISSUE TITLE
Appveyor and Travis are not open for viewing

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/SHiPS#70]
While the source code for SHiPS is open source, both the AppVeyor and Travis builds are closed.  This means that if a PR breaks tests, there's no way for contributors to know what caused it, unless they have access.

I wold suggest that as this is an open source project, that the CI builds be at least viewable by people who do not belong to the PowerShell (and I assume) Microsoft organisation.

**Comment by glennsarti** [comment]
@jianyunt This is still not fixed.  Travis is open but Appveyor still is not.

https://ci.appveyor.com/project/PowerShell/SHiPS/branch/development
```
Project not found or access denied.
```

**Comment by glennsarti** [comment]
Please reopen this issue.

**Comment by jianyunt** [comment]
fix is here https://github.com/PowerShell/SHiPS/pull/72

**Comment by jianyunt** [comment]
Thanks @glennsarti !
