### ISSUE TITLE
Support for Test-Path

### ISSUE THREAD

**Issue by murrahjm** [PowerShell/SHiPS#77]
Any plans to add support for using Test-Path against SHiPS paths?

**Comment by Tiberriver256** [comment]
Just as a note here. It does seem that test-path does work for partial paths but not for paths including the root.

Works:
```ps
PS MyCustomDrive:\> Test-Path ".\MyFolder\MyItem"
```

Doesn't work:
```ps
Test-Path MyCustomDrive:\MyFolder\MyItem
```

**Comment by jianyunt** [comment]
@murrahjm @Tiberriver256  Publish the ships module to the PowerShellGallery.com with the fixes.
